// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RolePlayingGame.Server;

namespace RolePlayingGame.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("RolePlayingGame.Server.Models.PlayerCharacterModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("Agility")
                        .HasColumnType("bigint");

                    b.Property<long>("BaseMana")
                        .HasColumnType("bigint");

                    b.Property<long>("BaseVigor")
                        .HasColumnType("bigint");

                    b.Property<long>("Charisma")
                        .HasColumnType("bigint");

                    b.Property<long>("Instinct")
                        .HasColumnType("bigint");

                    b.Property<long>("Intelligence")
                        .HasColumnType("bigint");

                    b.Property<long>("Mana")
                        .HasColumnType("bigint");

                    b.Property<long>("MaxMana")
                        .HasColumnType("bigint");

                    b.Property<long>("MaxVigor")
                        .HasColumnType("bigint");

                    b.Property<long>("Strength")
                        .HasColumnType("bigint");

                    b.Property<int>("Temperature")
                        .HasColumnType("integer");

                    b.Property<long>("Vigor")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("PlayerCharacters");
                });
#pragma warning restore 612, 618
        }
    }
}
